# Generated by Django 3.0 on 2020-10-09 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminDashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='documents/files/')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('DateApplied', models.DateTimeField(auto_now_add=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('OutstandingLeaveDays', models.IntegerField(default=26)),
                ('NumberOfDaystaken', models.IntegerField(null=True)),
                ('LeaveType', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity ', 'Maternity '), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate'), ('Terminal / Long term illness ', 'Terminal / Long term illness '), ('Study leave with pay ', 'Study leave with pay '), ('Leave without pay ', 'Leave without pay ')], max_length=300, null=True)),
                ('Approval_by_Line_Manager', models.CharField(default='Pending', max_length=10)),
                ('Approval_by_Director', models.CharField(default='Pending', max_length=10)),
                ('Approval_by_Executive_Director', models.CharField(default='Pending', max_length=10)),
                ('cancellation_status', models.BooleanField(default=False)),
                ('empDepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminDashboard.Departments')),
                ('empDirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.Director')),
                ('empDirectorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminDashboard.Directories')),
                ('file_upload', models.ManyToManyField(blank=True, to='employeeDashboard.Feed')),
            ],
            options={
                'verbose_name': 'Leave List',
                'verbose_name_plural': 'Applied leaves',
            },
        ),
        migrations.CreateModel(
            name='EventsHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event/Holiday name')),
                ('event_date', models.DateField(verbose_name='Date of Happening')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event or Holiday',
                'verbose_name_plural': 'Events and Holidays',
            },
        ),
    ]
